//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_pais
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fsituacion { get; set; }
        public string situacion { get; set; }
        public Nullable<int> estados_capital { get; set; }
        public string codigo_pais { get; set; }
    }
}
